from datetime import date
from typing import Protocol
from uuid import UUID

from app.contexts.metricas.domain.entities import MetricaSemanal, MetricasUsuarioMes


class MetricaRepository(Protocol):
    async def criar(self, metrica: MetricaSemanal) -> MetricaSemanal: ...
    async def por_id(self, metrica_id: UUID) -> MetricaSemanal | None: ...
    async def por_usuario_e_semana(
        self, usuario_id: UUID, semana_inicio: date
    ) -> MetricaSemanal | None: ...
    async def listar(
        self, usuario_id: UUID, mes: str | None, page: int, page_size: int
    ) -> tuple[list[MetricaSemanal], int]: ...
    async def atualizar(self, metrica: MetricaSemanal) -> MetricaSemanal: ...
    async def por_semanas(
        self, usuario_id: UUID, semanas: list[date]
    ) -> list[MetricaSemanal]: ...
    async def somar_por_mes(self, usuario_id: UUID, mes: str) -> dict[str, int]: ...
    async def listar_clientes_com_metricas_mes(
        self, mes: str
    ) -> list[MetricasUsuarioMes]: ...
