from typing import Protocol
from uuid import UUID

from app.contexts.conteudo.domain.entities import (
    Aula,
    Comentario,
    ComentarioLeitura,
    Modulo,
    Trilha,
)


class TrilhaRepository(Protocol):
    async def listar(self) -> list[Trilha]: ...
    async def por_id(self, trilha_id: UUID) -> Trilha | None: ...
    async def criar(self, trilha: Trilha) -> Trilha: ...
    async def atualizar(self, trilha: Trilha) -> Trilha: ...
    async def remover(self, trilha_id: UUID) -> None: ...
    async def reordenar(self, ordens: list[tuple[UUID, int]]) -> None: ...
    async def contar_aulas(self, trilha_id: UUID) -> int: ...


class ModuloRepository(Protocol):
    async def listar_por_trilha(self, trilha_id: UUID) -> list[Modulo]: ...
    async def por_id(self, modulo_id: UUID) -> Modulo | None: ...
    async def criar(self, modulo: Modulo) -> Modulo: ...
    async def atualizar(self, modulo: Modulo) -> Modulo: ...
    async def remover(self, modulo_id: UUID) -> None: ...
    async def reordenar(self, ordens: list[tuple[UUID, int]]) -> None: ...


class AulaRepository(Protocol):
    async def por_id(self, aula_id: UUID) -> Aula | None: ...
    async def listar_por_modulo(self, modulo_id: UUID) -> list[Aula]: ...
    async def criar(self, aula: Aula) -> Aula: ...
    async def atualizar(self, aula: Aula) -> Aula: ...
    async def remover(self, aula_id: UUID) -> None: ...
    async def reordenar(self, ordens: list[tuple[UUID, int]]) -> None: ...
    async def proxima(self, aula: Aula) -> Aula | None: ...


class AlunoAulaRepository(Protocol):
    async def marcar_concluida(self, usuario_id: UUID, aula_id: UUID) -> None: ...
    async def desmarcar(self, usuario_id: UUID, aula_id: UUID) -> None: ...
    async def concluidas_ids(self, usuario_id: UUID) -> set[UUID]: ...


class ComentarioRepository(Protocol):
    async def listar_por_aula(
        self, aula_id: UUID, page: int, page_size: int
    ) -> tuple[list[ComentarioLeitura], int]: ...
    async def por_id(self, comentario_id: UUID) -> Comentario | None: ...
    async def criar(self, comentario: Comentario) -> Comentario: ...
    async def atualizar(self, comentario: Comentario) -> Comentario: ...
    async def apagar(self, comentario_id: UUID) -> None: ...
