from typing import Protocol
from uuid import UUID

from app.contexts.content.domain.entities import (
    Lesson,
    Comment,
    CommentRead,
    Module,
    Track,
)


class TrackRepository(Protocol):
    async def list_all(self) -> list[Track]: ...
    async def get_by_id(self, trilha_id: UUID) -> Track | None: ...
    async def create(self, trilha: Track) -> Track: ...
    async def update(self, trilha: Track) -> Track: ...
    async def delete(self, trilha_id: UUID) -> None: ...
    async def reorder(self, ordens: list[tuple[UUID, int]]) -> None: ...
    async def count_lessons(self, trilha_id: UUID) -> int: ...


class ModuleRepository(Protocol):
    async def list_by_track(self, trilha_id: UUID) -> list[Module]: ...
    async def get_by_id(self, modulo_id: UUID) -> Module | None: ...
    async def create(self, modulo: Module) -> Module: ...
    async def update(self, modulo: Module) -> Module: ...
    async def delete(self, modulo_id: UUID) -> None: ...
    async def reorder(self, ordens: list[tuple[UUID, int]]) -> None: ...


class LessonRepository(Protocol):
    async def get_by_id(self, aula_id: UUID) -> Lesson | None: ...
    async def list_by_module(self, modulo_id: UUID) -> list[Lesson]: ...
    async def create(self, aula: Lesson) -> Lesson: ...
    async def update(self, aula: Lesson) -> Lesson: ...
    async def delete(self, aula_id: UUID) -> None: ...
    async def reorder(self, ordens: list[tuple[UUID, int]]) -> None: ...
    async def next_lesson(self, aula: Lesson) -> Lesson | None: ...


class StudentLessonRepository(Protocol):
    async def mark_completed(self, usuario_id: UUID, aula_id: UUID) -> None: ...
    async def unmark(self, usuario_id: UUID, aula_id: UUID) -> None: ...
    async def completed_ids(self, usuario_id: UUID) -> set[UUID]: ...


class CommentRepository(Protocol):
    async def list_by_lesson(
        self, aula_id: UUID, page: int, page_size: int
    ) -> tuple[list[CommentRead], int]: ...
    async def get_by_id(self, comentario_id: UUID) -> Comment | None: ...
    async def create(self, comentario: Comment) -> Comment: ...
    async def update(self, comentario: Comment) -> Comment: ...
    async def delete_comment(self, comentario_id: UUID) -> None: ...
