from typing import Protocol
from uuid import UUID

from app.domain.content_module.content_model import (
    Comment,
    CommentRead,
    Lesson,
    Module,
    Track,
)


class TrackRepository(Protocol):
    async def list_all(self) -> list[Track]: ...
    async def get_by_id(self, track_id: UUID) -> Track | None: ...
    async def create(self, track: Track) -> Track: ...
    async def update(self, track: Track) -> Track: ...
    async def delete(self, track_id: UUID) -> None: ...
    async def reorder(self, orders: list[tuple[UUID, int]]) -> None: ...


class ModuleRepository(Protocol):
    async def list_by_track(self, track_id: UUID) -> list[Module]: ...
    async def get_by_id(self, module_id: UUID) -> Module | None: ...
    async def create(self, module: Module) -> Module: ...
    async def update(self, module: Module) -> Module: ...
    async def delete(self, module_id: UUID) -> None: ...
    async def reorder(self, orders: list[tuple[UUID, int]]) -> None: ...


class LessonRepository(Protocol):
    async def get_by_id(self, lesson_id: UUID) -> Lesson | None: ...
    async def list_by_module(self, module_id: UUID) -> list[Lesson]: ...
    async def create(self, lesson: Lesson) -> Lesson: ...
    async def update(self, lesson: Lesson) -> Lesson: ...
    async def delete(self, lesson_id: UUID) -> None: ...
    async def reorder(self, orders: list[tuple[UUID, int]]) -> None: ...
    async def next_lesson(self, lesson: Lesson) -> Lesson | None: ...


class StudentLessonRepository(Protocol):
    async def mark_completed(self, user_id: UUID, lesson_id: UUID) -> None: ...
    async def unmark(self, user_id: UUID, lesson_id: UUID) -> None: ...
    async def completed_ids(self, user_id: UUID) -> set[UUID]: ...


class CommentRepository(Protocol):
    async def list_by_lesson(
        self, lesson_id: UUID, page: int, page_size: int
    ) -> tuple[list[CommentRead], int]: ...
    async def get_by_id(self, comment_id: UUID) -> Comment | None: ...
    async def create(self, comment: Comment) -> Comment: ...
    async def update(self, comment: Comment) -> Comment: ...
    async def delete_comment(self, comment_id: UUID) -> None: ...
