from typing import Protocol
from uuid import UUID

from app.domain.stage_module.stage_model import Stage, UserStage


class StageRepository(Protocol):
    async def create(self, stage: Stage) -> Stage: ...
    async def update(self, stage: Stage) -> Stage: ...
    async def delete(self, stage_id: UUID) -> None: ...
    async def get_by_id(self, stage_id: UUID) -> Stage | None: ...
    async def list_all(self) -> list[Stage]: ...
    async def list_for_user(self, user_id: UUID) -> list[tuple[UserStage, Stage]]: ...
    async def attach_to_user(self, user_id: UUID, stage_id: UUID) -> UserStage: ...
    async def detach_from_user(self, user_id: UUID, stage_id: UUID) -> None: ...
    async def set_done(self, user_id: UUID, stage_id: UUID, done: bool) -> UserStage: ...
