from datetime import date
from typing import Protocol
from uuid import UUID

from app.contexts.metrics.domain.entities import WeeklyMetric, UserMonthlyMetrics


class MetricRepository(Protocol):
    async def create(self, metrica: WeeklyMetric) -> WeeklyMetric: ...
    async def get_by_id(self, metrica_id: UUID) -> WeeklyMetric | None: ...
    async def por_usuario_e_semana(
        self, usuario_id: UUID, semana_inicio: date
    ) -> WeeklyMetric | None: ...
    async def list_all(
        self, usuario_id: UUID, mes: str | None, page: int, page_size: int
    ) -> tuple[list[WeeklyMetric], int]: ...
    async def update(self, metrica: WeeklyMetric) -> WeeklyMetric: ...
    async def por_semanas(self, usuario_id: UUID, semanas: list[date]) -> list[WeeklyMetric]: ...
    async def somar_por_mes(self, usuario_id: UUID, mes: str) -> dict[str, int]: ...
    async def listar_clientes_com_metricas_mes(self, mes: str) -> list[UserMonthlyMetrics]: ...
