from datetime import date
from typing import Protocol
from uuid import UUID

from app.contexts.metrics.domain.entities import WeeklyMetric, UserMonthlyMetrics


class MetricRepository(Protocol):
    async def create(self, metric: WeeklyMetric) -> WeeklyMetric: ...
    async def get_by_id(self, metric_id: UUID) -> WeeklyMetric | None: ...
    async def get_by_user_and_week(
        self, user_id: UUID, week_start: date
    ) -> WeeklyMetric | None: ...
    async def list_all(
        self, user_id: UUID, month: str | None, page: int, page_size: int
    ) -> tuple[list[WeeklyMetric], int]: ...
    async def update(self, metric: WeeklyMetric) -> WeeklyMetric: ...
    async def get_by_weeks(self, user_id: UUID, weeks: list[date]) -> list[WeeklyMetric]: ...
    async def sum_by_month(self, user_id: UUID, month: str) -> dict[str, int]: ...
    async def list_clients_with_metrics_month(self, month: str) -> list[UserMonthlyMetrics]: ...
