from datetime import date
from typing import Protocol
from uuid import UUID

from app.domain.metrics_module.metrics_model import Metric, MetricEntry


class MetricRepository(Protocol):
    # metric columns (definitions)
    async def create_metric(self, metric: Metric) -> Metric: ...
    async def update_metric(self, metric: Metric) -> Metric: ...
    async def delete_metric(self, metric_id: UUID) -> None: ...
    async def get_metric_by_id(self, metric_id: UUID) -> Metric | None: ...
    async def list_metrics(self, user_id: UUID) -> list[Metric]: ...
    # daily cells (entries)
    async def upsert_entry(self, metric_id: UUID, day: date, value: int) -> MetricEntry: ...
    async def delete_entry(self, metric_id: UUID, day: date) -> None: ...
    async def list_entries(
        self, user_id: UUID, start: date, end: date
    ) -> list[MetricEntry]: ...
