from typing import Protocol
from uuid import UUID

from app.domain.event_module.event_model import EventDate


class EventRepository(Protocol):
    async def create(self, event: EventDate) -> EventDate: ...
    async def update(self, event: EventDate) -> EventDate: ...
    async def delete(self, event_id: UUID) -> None: ...
    async def get_by_id(self, event_id: UUID) -> EventDate | None: ...
    async def list_for_admin(
        self, page: int, page_size: int
    ) -> tuple[list[EventDate], int]: ...
    async def list_for_client(
        self, client_id: UUID, page: int, page_size: int
    ) -> tuple[list[EventDate], int]: ...
    async def list_for_client_only(self, client_id: UUID) -> list[EventDate]: ...
    async def delete_by_year(self, year: int, scope: str) -> int: ...
