from typing import Protocol
from uuid import UUID

from app.domain.product_module.product_model import Product


class ProductRepository(Protocol):
    async def create(self, product: Product) -> Product: ...
    async def update(self, product: Product) -> Product: ...
    async def delete(self, product_id: UUID) -> None: ...
    async def get_by_id(self, product_id: UUID) -> Product | None: ...
    async def list_all(self) -> list[Product]: ...
